class DAG[T]:
    def add_node(self, node: T) -> None: ...
    def add_edge(self, source: T, target: T) -> None: ...
    def neighbors(self, node: T) -> list[T]: ...
    def remove_node(self, node: T) -> None: ...
    def remove_edge(self, source: T, target: T) -> None: ...
