version: "3"

networks:
  default:
    name: local-network

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgres
    ports:
      - 5432:5432

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306


  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis/redis-stack
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis/data:/data
