[project]
authors = [{ email = "julian.lf.olate@gmail", name = "olatejulian" }]
dependencies = ["pendulum>=2.1.2", "pydantic>=1.10.2", "python-dotenv>=0.21.0"]
description = "Clean arch and design patterns prototypes"
license = { text = "MIT" }
name = "python-seedwork"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.0"
