[project]
authors = [{ email = "julian.lf.olate@gmail.com", name = "olatejulian" }]
dependencies = ["pathspec>=0.12.1", "rich>=14.0.0", "typer>=0.15.2"]
description = "cli for simple list directory contents"
license = { text = "MIT" }
name = "pyls"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.0"
