[project]
authors = [{email = "julian.lf.olate@gmail.com", name = "olatejulian"}]
dependencies = [
  "SQLAlchemy>=1.4.36",
  "fastapi>=0.78.0",
  "python-dotenv>=0.20.0",
  "python-interface>=1.6.1"
]
description = ""
license = {text = "MIT"}
name = "storage"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.0.0"
