[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517>=1.0.0"]

[project]
authors = [{email = "julian.lf.olate@gmail.com", name = "olatejulian"}]
dependencies = ["pydantic>=1.10.2"]
description = ""
license = {text = "MIT"}
name = "inu_analyzer"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "0.1.0"

[tool.pdm]
